### ISSUE TITLE
Application plugin configuration startScripts update to work on Gradle 4.8

### ISSUE THREAD

**Issue by DJViking** [gradle-guides/building-java-9-modules#31]
<br />
The startScripts configuration in the Guide does not work with Gradle 4.8. Could it be outdated?

    djviking@machine:~/workspace/movies/build/distributions/movies-1.0-SNAPSHOT/bin> ./movies
    Error occurred during initialization of boot layer
    java.lang.module.FindException: Module com.djviking.movies.MoviesApplication not found

Then changed 

    --module: mainClassName
to

    --module: moduleName

A different error message:

    djviking@machine:~/workspace/movies/build/distributions/movies-1.0-SNAPSHOT/bin> ./movies
    module com.djviking.movies does not have a MainClass attribute, use -m <module>/<main-class>

This gave me a clue what to change:
Then changed to

    '--module', moduleName+'/'+mainClassName

One step further, but still fails:

Exception in Application start method

    java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at 
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:941)
    Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
        at java.base/java.lang.Thread.run(Thread.java:844)
    Caused by: javafx.fxml.LoadException: 
    file:///home/djviking/workspace/movies/build/distributions/movies-1.0-SNAPSHOT/lib/movies-1.0-SNAPSHOT.jar!/com/djviking/movies/movies.fxml:10

        at javafx.fxml/javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2625)
        at javafx.fxml/javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:105)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:943)
        at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:980)
        at javafx.fxml/javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:227)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:752)
        at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
        at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
        at com.djviking.movies/no.smeaworks.movies.MoviesApplication.start(MoviesApplication.java:24)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        ... 1 more
    Caused by: java.lang.IllegalAccessException: class javafx.fxml.FXMLLoader$ValueElement (in module javafx.fxml) cannot access class no.smeaworks.movies.MoviesController (in module no.smeaworks.movies) because module no.smeaworks.movies does not export no.smeaworks.movies to module javafx.fxml
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:360)
        at java.base/jdk.internal.reflect.Reflection.ensureMemberAccess(Reflection.java:107)
        at java.base/java.lang.Class.newInstance(Class.java:555)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:936)
        ... 17 more
    Exception running application com.djviking.movies.MoviesApplication

Finally fixed by adding this to my module-info.java
    exports no.smeaworks.movies to javafx.graphics, javafx.fxml;
    opens no.smeaworks.movies to javafx.graphics, javafx.fxml;

Then the startScript works.
Wanted to mention this if helpful to update this section in the Guide.
Running gradle run does not need this exports/opens to javafx.fxml.

The change would seem to be to update the Guide to:

    '--module', moduleName+'/'+mainClassName

Perhaps moduleName missing from the Guide, or this has changed in Gradle 4.8

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #238](https://github.com/gradle/guides/issues/238) via [**ZenHub**](https://www.zenhub.com/)
