### ISSUE TITLE
Tests can not create objects...

### ISSUE THREAD

**Issue by Novanic** [gradle-guides/building-java-9-modules#35]
When I try to run my tests with using the module-path instead of the class-path, I get the following exception. JUnit can not access the constructor of a class which is not within the module-path? In my opinion JUnit should have access to all resources (white box testing). Extending the productive module-info can not be the solution (I want to access it only under test).

To use the module-info / module-path under test is required in my project to use the ServiceLoader.

Any suggestions? :-)

java.lang.reflect.InaccessibleObjectException: Unable to make public xy.pattern.XYTest() accessible: module xy does not "exports xy.pattern" to module org.junit.platform.commons
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:192)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:185)
	at org.junit.platform.commons@1.4.2/org.junit.platform.commons.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:1512)
	at org.junit.platform.commons@1.4.2/org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:453)

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #273](https://github.com/gradle/guides/issues/273) via [**ZenHub**](https://www.zenhub.com/)
